# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  compose:up:
    desc: "run all docker compose services"
    cmd: docker compose up -d
  
  compose:down:
    desc: "stop all running docker compose services"
    cmd: docker compose down

  db:cli:
    desc: "access postgres db cli"
    cmd: docker exec -it postgres psql -U {{ .DB_USER }} -b {{ .DB_NAME }}

  db:migrate:
    desc: "run database migrations"
    cmd: go run cmd/migrate/main.go

  dev:
    desc: "run backend api in dev mode"
    cmd: air

  swagger:gen:
    desc: "generate swagger api documentation"
    cmd: swag init -g cmd/http/main.go -o docs --parseDependency --parseInternal
