// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one


SELECT COUNT(*) FROM jobs
`

// page_offset
// ---------------------------------------------------------------------------
// CountJobs
// Companion to ListJobsOffset for total-page-count metadata.
// ---------------------------------------------------------------------------
func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one


INSERT INTO jobs (
    title,
    description,
    company,
    location,
    salary_min,
    salary_max,
    created_by
)
VALUES (
    $1,  -- title
    $2,  -- description
    $3,  -- company
    $4,  -- location
    $5,  -- salary_min  (nullable)
    $6,  -- salary_max  (nullable)
    $7   -- created_by  (UUID of authenticated admin)
)
RETURNING
    id,
    title,
    description,
    company,
    location,
    salary_min,
    salary_max,
    created_by,
    created_at,
    updated_at
`

type CreateJobParams struct {
	Title       string
	Description string
	Company     string
	Location    string
	SalaryMin   pgtype.Int8
	SalaryMax   pgtype.Int8
	CreatedBy   pgtype.UUID
}

// =============================================================================
// queries/job.sql
// Maps to: internal/core/port/job.go → JobRepository interface
// Write operations (CreateJob, DeleteJob) are Admin-only — enforced at the
// routing layer via RoleMiddleware(domain.AdminRole), not here.
// =============================================================================
// ---------------------------------------------------------------------------
// CreateJob
// Called by: JobService.CreateJob  (POST /jobs — AdminRole only)
// created_by references the authenticated admin's user ID extracted from
// the JWT claims in middleware.
// ---------------------------------------------------------------------------
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.Description,
		arg.Company,
		arg.Location,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.CreatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Company,
		&i.Location,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

// ---------------------------------------------------------------------------
// DeleteJob
// Called by: JobService.DeleteJob  (DELETE /jobs/:id — AdminRole only)
// Hard delete; add a deleted_at column + soft-delete variant if audit trails
// are required.
// ---------------------------------------------------------------------------
func (q *Queries) DeleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJobByID = `-- name: GetJobByID :one
SELECT
    j.id,
    j.title,
    j.description,
    j.company,
    j.location,
    j.salary_min,
    j.salary_max,
    j.created_by,
    u.name AS created_by_name,
    j.created_at,
    j.updated_at
FROM jobs j
JOIN users u ON u.id = j.created_by
WHERE j.id = $1
LIMIT 1
`

type GetJobByIDRow struct {
	ID            pgtype.UUID
	Title         string
	Description   string
	Company       string
	Location      string
	SalaryMin     pgtype.Int8
	SalaryMax     pgtype.Int8
	CreatedBy     pgtype.UUID
	CreatedByName string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// GetJobByID
// Called by: JobService.GetJobById  (GET /jobs/:id — UserRole+)
// ---------------------------------------------------------------------------
func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (GetJobByIDRow, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Company,
		&i.Location,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT
    j.id,
    j.title,
    j.description,
    j.company,
    j.location,
    j.salary_min,
    j.salary_max,
    j.created_by,
    u.name AS created_by_name,
    j.created_at,
    j.updated_at
FROM jobs j
JOIN users u ON u.id = j.created_by
WHERE (j.created_at, j.id) < ($1, $2)   -- keyset cursor
ORDER BY
    j.created_at DESC,
    j.id          DESC
LIMIT $3
`

type ListJobsParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
	Limit       int32
}

type ListJobsRow struct {
	ID            pgtype.UUID
	Title         string
	Description   string
	Company       string
	Location      string
	SalaryMin     pgtype.Int8
	SalaryMax     pgtype.Int8
	CreatedBy     pgtype.UUID
	CreatedByName string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// ListJobs
// Called by: JobService.GetJobs  (GET /jobs — UserRole+)
// Keyset pagination on (created_at, id) for stable ordering on large tables.
// Pass cursor_created_at = 'infinity' and cursor_id = gen_random_uuid()
// for the first page, then use the last row's values for subsequent pages.
// ---------------------------------------------------------------------------
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.CreatedAt, arg.CreatedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Company,
			&i.Location,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.CreatedBy,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsOffset = `-- name: ListJobsOffset :many


SELECT
    j.id,
    j.title,
    j.company,
    j.location,
    j.salary_min,
    j.salary_max,
    j.created_at
FROM jobs j
ORDER BY j.created_at DESC
LIMIT  $1   -- page_size
OFFSET $2
`

type ListJobsOffsetParams struct {
	Limit  int32
	Offset int32
}

type ListJobsOffsetRow struct {
	ID        pgtype.UUID
	Title     string
	Company   string
	Location  string
	SalaryMin pgtype.Int8
	SalaryMax pgtype.Int8
	CreatedAt pgtype.Timestamptz
}

// page_size
// ---------------------------------------------------------------------------
// ListJobsOffset
// Simple LIMIT/OFFSET alternative if keyset pagination is not wired yet.
// Prefer ListJobs (keyset) for production — offset degrades on large tables.
// ---------------------------------------------------------------------------
func (q *Queries) ListJobsOffset(ctx context.Context, arg ListJobsOffsetParams) ([]ListJobsOffsetRow, error) {
	rows, err := q.db.Query(ctx, listJobsOffset, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsOffsetRow
	for rows.Next() {
		var i ListJobsOffsetRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJobs = `-- name: SearchJobs :many
SELECT
    j.id,
    j.title,
    j.company,
    j.location,
    j.salary_min,
    j.salary_max,
    j.created_at,
    ts_rank(to_tsvector('english', j.title), plainto_tsquery('english', $1)) AS rank
FROM jobs j
WHERE to_tsvector('english', j.title) @@ plainto_tsquery('english', $1)
ORDER BY rank DESC
LIMIT $2
`

type SearchJobsParams struct {
	PlaintoTsquery string
	Limit          int32
}

type SearchJobsRow struct {
	ID        pgtype.UUID
	Title     string
	Company   string
	Location  string
	SalaryMin pgtype.Int8
	SalaryMax pgtype.Int8
	CreatedAt pgtype.Timestamptz
	Rank      float32
}

// ---------------------------------------------------------------------------
// SearchJobs
// Full-text search on title using the GIN index defined in the migration.
// Useful extension point — not in the original README but common in job APIs.
// ---------------------------------------------------------------------------
func (q *Queries) SearchJobs(ctx context.Context, arg SearchJobsParams) ([]SearchJobsRow, error) {
	rows, err := q.db.Query(ctx, searchJobs, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchJobsRow
	for rows.Next() {
		var i SearchJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.CreatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET
    title       = COALESCE($2, title),
    description = COALESCE($3, description),
    company     = COALESCE($4, company),
    location    = COALESCE($5, location),
    salary_min  = COALESCE($6, salary_min),
    salary_max  = COALESCE($7, salary_max),
    updated_at  = NOW()
WHERE id = $1
RETURNING
    id,
    title,
    description,
    company,
    location,
    salary_min,
    salary_max,
    created_by,
    updated_at
`

type UpdateJobParams struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Company     string
	Location    string
	SalaryMin   pgtype.Int8
	SalaryMax   pgtype.Int8
}

type UpdateJobRow struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Company     string
	Location    string
	SalaryMin   pgtype.Int8
	SalaryMax   pgtype.Int8
	CreatedBy   pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// UpdateJob
// Called by: JobService.UpdateJob  (PATCH /jobs/:id — AdminRole only)
// Only non-null arguments update their respective columns (COALESCE pattern).
// ---------------------------------------------------------------------------
func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (UpdateJobRow, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Company,
		arg.Location,
		arg.SalaryMin,
		arg.SalaryMax,
	)
	var i UpdateJobRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Company,
		&i.Location,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
