// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Write operations (POST, DELETE) are scoped to Admin role (5150) only.
type Job struct {
	ID          pgtype.UUID
	Title       string
	Description string
	Company     string
	Location    string
	SalaryMin   pgtype.Int8
	SalaryMax   pgtype.Int8
	// Admin user who created the listing
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Supports token rotation + reuse detection. Reused tokens trigger full session revocation.
type RefreshToken struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	// SHA-256 hash — raw token never persisted
	TokenHash string
	// Set on reuse detection (ErrTokenReuse)
	IsRevoked bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Passwords and tokens are never stored in plaintext. Tokens stored as SHA-256 hashes.
type User struct {
	ID    pgtype.UUID
	Name  string
	Email string
	// bcrypt with secure cost factor
	PasswordHash string
	// 2001=User, 5150=Admin
	Role            int32
	IsEmailVerified bool
	// SHA-256 hash of one-time token
	EmailVerifyTokenHash      pgtype.Text
	EmailVerifyTokenExpiresAt pgtype.Timestamptz
	// SHA-256 hash of one-time token
	PasswordResetTokenHash      pgtype.Text
	PasswordResetTokenExpiresAt pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
}
