// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveRefreshTokens = `-- name: CountActiveRefreshTokens :one
SELECT COUNT(*)
FROM refresh_tokens
WHERE user_id   = $1
  AND is_revoked = FALSE
  AND expires_at > NOW()
`

// ---------------------------------------------------------------------------
// CountActiveRefreshTokens
// Optional: useful for an admin endpoint or health metrics to monitor
// active session count per user.
// ---------------------------------------------------------------------------
func (q *Queries) CountActiveRefreshTokens(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRefreshTokens, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one


INSERT INTO refresh_tokens (
    user_id,
    token_hash,
    expires_at
)
VALUES (
    $1,  -- user_id
    $2,  -- SHA-256(raw_token)
    $3   -- NOW() + REFRESH_TOKEN_DURATION
)
RETURNING
    id,
    user_id,
    token_hash,
    is_revoked,
    expires_at,
    created_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// =============================================================================
// queries/refresh_token.sql
// Maps to: internal/core/port/auth.go → AuthRepository interface
// Implements JWT rotation and ErrTokenReuse detection.
//
// Token lifecycle:
//
//	Issue  → CreateRefreshToken         (on login / successful refresh)
//	Rotate → GetRefreshToken +
//	          RevokeRefreshToken +
//	          CreateRefreshToken        (on POST /refresh)
//	Reuse  → RevokeAllUserRefreshTokens (on ErrTokenReuse — full session wipe)
//	Logout → RevokeAllUserRefreshTokens
//
// =============================================================================
// ---------------------------------------------------------------------------
// CreateRefreshToken
// Called after successful login or token rotation.
// Raw token NEVER stored — only SHA-256(raw_token) persists.
// ---------------------------------------------------------------------------
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at  < NOW()
  AND is_revoked  = TRUE
`

// ---------------------------------------------------------------------------
// DeleteExpiredRefreshTokens
// Maintenance query — run periodically (e.g. cron / scheduled job) to prune
// rows that are both expired and revoked, keeping the table lean.
// ---------------------------------------------------------------------------
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT
    id,
    user_id,
    token_hash,
    is_revoked,
    expires_at,
    created_at
FROM refresh_tokens
WHERE token_hash = $1   -- SHA-256(raw_token from HttpOnly cookie)
LIMIT 1
`

// ---------------------------------------------------------------------------
// GetRefreshToken
// Called on POST /refresh to locate the record before rotation.
// Application layer checks: is_revoked, expires_at — raises ErrTokenReuse
// if is_revoked = TRUE.
// ---------------------------------------------------------------------------
func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE user_id  = $1
  AND is_revoked = FALSE
`

// ---------------------------------------------------------------------------
// RevokeAllUserRefreshTokens
// Called on:
//
//	(a) POST /logout  — intentional session termination
//	(b) ErrTokenReuse — a consumed token was replayed; full session wipe
//	    signals a potential token theft scenario.
//
// ---------------------------------------------------------------------------
func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE id = $1
`

// ---------------------------------------------------------------------------
// RevokeRefreshToken
// Called during normal token rotation to invalidate the consumed token.
// The old row is revoked; CreateRefreshToken then issues a fresh row.
// ---------------------------------------------------------------------------
func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
