// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one


SELECT COUNT(*) FROM users
`

// page_offset
// ---------------------------------------------------------------------------
// CountUsers
// Companion to ListUsers for pagination metadata.
// ---------------------------------------------------------------------------
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one


INSERT INTO users (
    name,
    email,
    password_hash,
    role
)
VALUES (
    $1,  -- name
    $2,  -- email
    $3,  -- password_hash  (bcrypt, never plaintext)
    $4   -- role           ('user' | 'admin')
)
RETURNING
    id,
    name,
    email,
    role,
    is_email_verified,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	Role         int32
}

type CreateUserRow struct {
	ID              pgtype.UUID
	Name            string
	Email           string
	Role            int32
	IsEmailVerified bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// =============================================================================
// queries/user.sql
// Maps to: internal/core/port/user.go → UserRepository interface
// =============================================================================
// ---------------------------------------------------------------------------
// CreateUser
// Called by: UserService.RegisterUser
// ---------------------------------------------------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    name,
    email,
    password_hash,
    role,
    is_email_verified,
    email_verify_token_hash,
    email_verify_token_expires_at,
    password_reset_token_hash,
    password_reset_token_expires_at,
    created_at,
    updated_at
FROM users
WHERE email = $1
LIMIT 1
`

// ---------------------------------------------------------------------------
// GetUserByEmail
// Called by: AuthService.Login, AuthService.RequestPasswordReset
// Note: returns full row including password_hash for credential comparison.
// ---------------------------------------------------------------------------
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsEmailVerified,
		&i.EmailVerifyTokenHash,
		&i.EmailVerifyTokenExpiresAt,
		&i.PasswordResetTokenHash,
		&i.PasswordResetTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailVerifyToken = `-- name: GetUserByEmailVerifyToken :one
SELECT
    id,
    name,
    email,
    role,
    is_email_verified,
    email_verify_token_hash,
    email_verify_token_expires_at,
    updated_at
FROM users
WHERE email_verify_token_hash = $1   -- SHA-256(raw_token from query param)
LIMIT 1
`

type GetUserByEmailVerifyTokenRow struct {
	ID                        pgtype.UUID
	Name                      string
	Email                     string
	Role                      int32
	IsEmailVerified           bool
	EmailVerifyTokenHash      pgtype.Text
	EmailVerifyTokenExpiresAt pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// GetUserByEmailVerifyToken
// Called by: UserService.VerifyEmail (GET /confirm-email?token=…)
// Looks up the hashed token; application layer validates expiry + marks verified.
// ---------------------------------------------------------------------------
func (q *Queries) GetUserByEmailVerifyToken(ctx context.Context, emailVerifyTokenHash pgtype.Text) (GetUserByEmailVerifyTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailVerifyToken, emailVerifyTokenHash)
	var i GetUserByEmailVerifyTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.IsEmailVerified,
		&i.EmailVerifyTokenHash,
		&i.EmailVerifyTokenExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    name,
    email,
    role,
    is_email_verified,
    created_at,
    updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID              pgtype.UUID
	Name            string
	Email           string
	Role            int32
	IsEmailVerified bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// GetUserByID
// Called by: AuthService.RefreshToken (token claims → user lookup)
// ---------------------------------------------------------------------------
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.IsEmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPasswordResetToken = `-- name: GetUserByPasswordResetToken :one
SELECT
    id,
    email,
    password_reset_token_hash,
    password_reset_token_expires_at
FROM users
WHERE password_reset_token_hash = $1   -- SHA-256(raw_token from request body)
LIMIT 1
`

type GetUserByPasswordResetTokenRow struct {
	ID                          pgtype.UUID
	Email                       string
	PasswordResetTokenHash      pgtype.Text
	PasswordResetTokenExpiresAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// GetUserByPasswordResetToken
// Called by: AuthService.ResetPassword
// Application layer must still check expires_at before accepting the token.
// ---------------------------------------------------------------------------
func (q *Queries) GetUserByPasswordResetToken(ctx context.Context, passwordResetTokenHash pgtype.Text) (GetUserByPasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByPasswordResetToken, passwordResetTokenHash)
	var i GetUserByPasswordResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordResetTokenHash,
		&i.PasswordResetTokenExpiresAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    name,
    email,
    role,
    is_email_verified,
    created_at,
    updated_at
FROM users
ORDER BY created_at DESC
LIMIT  $1   -- page_size
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID              pgtype.UUID
	Name            string
	Email           string
	Role            int32
	IsEmailVerified bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// ListUsers
// Called by: UserService.GetUsers  (Admin-only endpoint: GET /users)
// Paginated with LIMIT / OFFSET for large result sets.
// ---------------------------------------------------------------------------
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.IsEmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET
    is_email_verified             = TRUE,
    email_verify_token_hash       = NULL,
    email_verify_token_expires_at = NULL,
    updated_at                    = NOW()
WHERE id = $1
`

// ---------------------------------------------------------------------------
// MarkEmailVerified
// Called by: UserService.VerifyEmail after token validation passes.
// Clears token columns atomically.
// ---------------------------------------------------------------------------
func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setEmailVerifyToken = `-- name: SetEmailVerifyToken :exec
UPDATE users
SET
    email_verify_token_hash       = $2,   -- SHA-256(raw_token)
    email_verify_token_expires_at = $3,   -- NOW() + EMAIL_TOKEN_DURATION
    updated_at                    = NOW()
WHERE id = $1
`

type SetEmailVerifyTokenParams struct {
	ID                        pgtype.UUID
	EmailVerifyTokenHash      pgtype.Text
	EmailVerifyTokenExpiresAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// SetEmailVerifyToken
// Called by: UserService.SendVerificationEmail
// Stores SHA-256 hash; raw token is emailed to the user only.
// ---------------------------------------------------------------------------
func (q *Queries) SetEmailVerifyToken(ctx context.Context, arg SetEmailVerifyTokenParams) error {
	_, err := q.db.Exec(ctx, setEmailVerifyToken, arg.ID, arg.EmailVerifyTokenHash, arg.EmailVerifyTokenExpiresAt)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users
SET
    password_reset_token_hash       = $2,   -- SHA-256(raw_token)
    password_reset_token_expires_at = $3,   -- NOW() + reset window
    updated_at                      = NOW()
WHERE email = $1
`

type SetPasswordResetTokenParams struct {
	Email                       string
	PasswordResetTokenHash      pgtype.Text
	PasswordResetTokenExpiresAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// SetPasswordResetToken
// Called by: AuthService.RequestPasswordReset
// Enumeration-safe: the handler always returns 200 regardless of match.
// ---------------------------------------------------------------------------
func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.Email, arg.PasswordResetTokenHash, arg.PasswordResetTokenExpiresAt)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET
    name       = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    name,
    email,
    role,
    is_email_verified,
    updated_at
`

type UpdateUserNameParams struct {
	ID   pgtype.UUID
	Name string
}

type UpdateUserNameRow struct {
	ID              pgtype.UUID
	Name            string
	Email           string
	Role            int32
	IsEmailVerified bool
	UpdatedAt       pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// UpdateUserName
// Called by: UserService.UpdateUser (profile edits)
// ---------------------------------------------------------------------------
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UpdateUserNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i UpdateUserNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.IsEmailVerified,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password_hash                   = $2,   -- new bcrypt hash
    password_reset_token_hash       = NULL,
    password_reset_token_expires_at = NULL,
    updated_at                      = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

// ---------------------------------------------------------------------------
// UpdateUserPassword
// Called by: AuthService.ResetPassword (after token validation)
// Clears the reset token atomically in the same statement.
// ---------------------------------------------------------------------------
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
